library(maptools)
library(spdep)
cattle_production <- readShapePoly("cattle_production",IDvar="OBJECTID") 
coords <- coordinates(cattle_production)
plot(cattle_production, border="blue", axes=TRUE) 
points(coords, cex=0.8)
knn1IT <- knn2nb(knearneigh(coords,k=1,longlat=T))
plot(cattle_production, border="grey")
plot(knn1IT, coords, add=TRUE) 
knn4IT <- knn2nb(knearneigh(coords,k=4,longlat=T))
plot(cattle_production, border="cyan")
plot(knn4IT, coords, add=TRUE) 

